### ISSUE TITLE
Re-add Test.fuzz4, Test.fuzz5?

### ISSUE THREAD

**Issue by ianmackenzie** [elm-explorations/test#10]
When updating some of my tests to use this package, I ran into a few places where I was using `Test.fuzz4`. My initial solution was to use `Fuzz.map4` to map the four arguments into a record, and rewrite my expectation function to take a single record argument, but this seemed pretty messy (introduced some pretty meaningless record types). I ended up writing my own module to replicate  `Test.fuzz4`:

```elm
module Test.FuzzN exposing (fuzz4)

import Expect exposing (Expectation)
import Fuzz exposing (Fuzzer)
import Test exposing (Test)


type alias Arguments4 a b c d =
    { argument1 : a
    , argument2 : b
    , argument3 : c
    , argument4 : d
    }


fuzz4 : Fuzzer a -> Fuzzer b -> Fuzzer c -> Fuzzer d -> String -> (a -> b -> c -> d -> Expectation) -> Test
fuzz4 fuzzer1 fuzzer2 fuzzer3 fuzzer4 description expectation =
    Test.fuzz
        (Fuzz.map4 Arguments4 fuzzer1 fuzzer2 fuzzer3 fuzzer4)
        description
        (\{ argument1, argument2, argument3, argument4 } ->
            expectation argument1 argument2 argument3 argument4
        )
```

(The actual module also implements `fuzz5` for completeness.) I realize that `Test.fuzz4` and `Test.fuzz5` can no longer be described as alternatives to `Fuzz.tuple4` and `Fuzz.tuple5`, so the documentation wording would need to be updated, but I think it makes sense to continue to support them (just like `Fuzz.map4` and `Fuzz.map5` are still supported).

Thoughts? Would a pull request be welcome? If so, is the above implementation a good one? (Wasn't sure if it might cause issues for shrinking or error message generation, for example...)

**Comment by mgold** [comment]
It definitely gets harder to effectively shrink with more fuzzers, and arguably we should be guiding users into fuzzing the things they think will change the most.

Another use case is testing a function like `ComplexThing -> String -> Output`, where you need many different fields to construct `thing : ComplexThing`. You should define a fuzzer for that type instead.

All that said, I think I'd be okay adding these, maybe in a different section that discourages their use, but at least they'd be there.

**Comment by mgold** [comment]
I'm good with that.
