### ISSUE TITLE
No (obvious) way to generate recursive fuzzers

### ISSUE THREAD

**Issue by zenhack** [elm-explorations/test#102]
I'm working on adding decode support to `commonmind/elm-csexpr`, and as part of testing, I want a fuzzer for this type:

```elm
type CSexpr
    = Atom String
    | List (List CSexpr)
```

The obvious (but wrong) thing to write would be:

```elm
csexprFuzzer = Fuzz.oneOf
    [ Fuzz.map Atom Fuzz.string
    , Fuzz.map List <| Fuzz.list csexprFuzzer
    ]
```

It doesn't work because it would blow the stack, and elm catches this at compile time. However, I can't find away to work around this.

One possible extension to the library that would make this feasible would be something like:

```elm
{-| `lazy f` is the same as `f ()`, except that its evaluation is delayed, which is useful when
defining fuzzers recursively
-}
lazy : (() -> Fuzzer a) -> Fuzzer a
```

**Comment by mgold** [comment]
It's a bit more complicated than laziness.

For random generation of recursive values, you need some kind of depth limit at which point the fuzzer returns a base case. How deep is deep enough varies by use case. Some types can have multiple base cases and multiple recursive cases, with some recursive cases blowing up much faster than others. See [this file](https://github.com/mgold/elm-geojson/blob/master/tests/Tests.elm) for fuzzing a non-trivial recursive data structure.

**Comment by lydell** [comment]
@mgold Thanks for sharing that example. Using it, I managed to write a recursive fuzzer for a use case I had (JSON data). I wrote a little helper function called `recursiveFuzzer`. In case it helps anyone else, here it is:

https://github.com/lydell/elm-jason/blob/140852cbf39ca63ba732c6a46da0e463930d9b67/tests/Decode.elm#L13-L60

**Comment by rupertlssmith** [comment]
@lydell Nice helper function - thanks :+1:
