### ISSUE TITLE
Where are the fuzzN fuzzers?

### ISSUE THREAD

**Issue by dwayne** [elm-explorations/test#104]
The documentation for the tuple fuzzers says:

> Instead of using a tuple, consider using `fuzzN`.

I think the documentation maybe incorrect.

**Comment by harrysarson** [comment]
Here! 

* https://package.elm-lang.org/packages/elm-explorations/test/latest/Test#fuzz2
* https://package.elm-lang.org/packages/elm-explorations/test/latest/Test#fuzz3

Saying that, it would be much clearer if we replace "`fuzzN`" by "`fuzz2` and `fuzz3`". A couple of links might be icing on the cake.

**Comment by mgold** [comment]
I think `fuzzN` was back from when they went up to `fuzz5`. Since there are only two now, Harry's suggestion sounds fine.

**Comment by dwayne** [comment]
Using the `fuzzN` terminology was fine. I wasn't looking for `fuzz` with an `N`. I just didn't notice that `fuzz2`, `fuzz3` etc was exported from `Test`.

But yes, Harry's suggestion sounds fine and the addition of links will be even better.
