### ISSUE TITLE
NaN and Infinity in Fuzzers

### ISSUE THREAD

**Issue by gampleman** [elm-explorations/test#118]
Floating point numbers have some special values that behave in difficult ways:

- `Infinity` and `-Infinity`
- `NaN`
- overflow close values like `Number.MAX_VALUE`, etc
- `0`

If I am trying to write robust code, then testing it with these values is reasonable (especially for code that crosses boundaries, like library code's public API - I've had bugs reported which were due to NaN being passed in). 

On the other hand, there are many reasonable properties that don't hold on these specific values. I would propose to have the basic `float` fuzzer include these values, but perhaps have a more specific fuzzer (`safeFloat` or something?) that doesn't.

**Comment by mgold** [comment]
You're welcome to build your own fuzzer based on `Fuzz.float` with `Fuzz.frequency` and `Fuzz.constant`. The thinking is that if you want these misbehaving values, you can add them in as you see fit. But if `Fuzz.float` generated them out of the box, there would be no way to opt out of them.

**Comment by gampleman** [comment]
I guess for me the question is: if this test asserts that the property holds for **any** float, but then the property doesn't actually hold in production, then I would say that my tests have failed me\*. So I would prefer if I was forced to explicitly acknowledge the conditions under which the property holds.

---
\* Not that property tests "prove" anything, but if my property fails just in the situation where `a = 3223.0439535` and `b=4343`, the probability is different than if `a = NaN` and `b` can be anything.

**Comment by drathier** [comment]
Yeah, something like `Fuzz.float {infinitiy=True, nan=False}` would clearly show whether or not it'll generate those special values.

**Comment by gampleman** [comment]
This has now been implemented in elm-test@2.
