### ISSUE TITLE
Wrong error message when using Expect.equal on a float

### ISSUE THREAD

**Issue by tgelu** [elm-explorations/test#122]
Using ``Expect.equal 0.3 0.3`` for example produces the following error ``Do not use Expect.equal with floats. Use Float.within instead.``

I naturally assumed I will just import ``Float`` in such a case, but of course what the message really wanted to say is that I should use ``Expect.within`` instead, not ``Float.within``.

**Comment by harrysarson** [comment]
This looks like a bug to me. :bug: Offending lines are:

https://github.com/elm-explorations/test/blob/21469557c96df825c2a003d452993258694c14e1/src/Expect.elm#L809
https://github.com/elm-explorations/test/blob/21469557c96df825c2a003d452993258694c14e1/src/Expect.elm#L812

**Comment by tgelu** [comment]
@harrysarson - I can see it's fixed in master, but not released.

**Comment by harrysarson** [comment]
Aha!

**Comment by drathier** [comment]
It's fixed on master but hasn't been released yet. Sorry about that, I'm not sure when the next release will be. https://github.com/elm-explorations/test/blob/master/src/Expect.elm#L742
