### ISSUE TITLE
Elm 0.19.1 support

### ISSUE THREAD

**Issue by aminnairi** [elm-explorations/test#125]
Hi there,

It seems like this package has became incompatible with the version 0.19.1 of Elm.

I am not aware of the requirements needed to support this version but I would like to help if someone know what to do!

![image](https://user-images.githubusercontent.com/18418459/75380307-131b7180-58d7-11ea-91e5-9345910c78d0.png)

**Comment by avh4** [comment]
The current version is now called `elm-explorations/test` (not `elm-community`): https://package.elm-lang.org/packages/elm-explorations/test/latest/

**Comment by aminnairi** [comment]
Oh my bad. Closing then. Thanks for your answer.
