### ISSUE TITLE
Add a `--color=never` option

### ISSUE THREAD

**Issue by HarrisonMc555** [elm-explorations/test#127]
When running `elm-test` in a "`DUMB`" terminal (in my case, Emacs), color escape sequences don't work. This would also be a concern if someone were storing the output of `elm-test` in a text file.

Most command-line tools that provide colors also provide a `--colors` option that can be set to `auto`, `always`, or `never`. At the very least, could we provide a `yes`/`no` option (and default to `yes`)?

**Comment by jfmengels** [comment]
`elm-test --no-color` achieves this purpose. I think documenting it better would solve this issue.

**Comment by lydell** [comment]
From `elm-test --help` these days:

```
  --no-color          Disable colored console output (setting FORCE_COLOR=0 also works)
  --color             Force colored console output (setting FORCE_COLOR to anything but 0 also works)
```

I think this issue can be closed.

**Comment by Janiczek** [comment]
Thank you both for triaging!
