### ISSUE TITLE
Incorporate elm-html-test

### ISSUE THREAD

**Issue by rtfeldman** [elm-explorations/test#13]
For several reasons...

* Many people seem unaware http://package.elm-lang.org/packages/eeue56/elm-html-test/latest is available (which is a shame - it rocks!)
* There's no more native whitelist, so it can't be re-published in 0.19 as-is
* This project is going to have more dependencies on other packages when it gets into testing `Cmd` values anyway

...the plan is to add `elm-html-test` here.

This will entail the usual 0.19 changes, plus `Native` -> `Kernel`, and updating the README and other docs.

**Comment by rtfeldman** [comment]
Note: @eeue56 has already started working on this.

**Comment by gyzerok** [comment]
There is also longstanding issue/pr from me there https://github.com/eeue56/elm-html-test/pull/65. Probably there was not enough time to look into it due to all the work around 0.19. Would appreciate if it could be batched with the work mentioned here.

**Comment by avh4** [comment]
Taking a look at this now (though don't expect to finish today)

**Comment by avh4** [comment]
WIP: https://github.com/elm-explorations/test/pull/41

A notable problem is the removal of Debug.crash, which is going is looking like it will needs a bit of non-trivial refactoring to get around.

**Comment by andys8** [comment]
#41 is merged, `1.2.0` released. I guess this issue can be closed :+1:

**Comment by avh4** [comment]
Thanks! I updated the README in https://github.com/elm-explorations/test/commit/13bc9baca36675c1062d2764dab822b445b318b2, and also realized that we haven't merged in elm-html-test's old README, so I created an issue for that: https://github.com/elm-explorations/test/issues/51
