### ISSUE TITLE
Windows 10 The command line is too long

### ISSUE THREAD

**Issue by YauhenPylAurea** [elm-explorations/test#131]
There is the following issue (more than 500 tests and around 200 files of tests)

![image](https://user-images.githubusercontent.com/42114592/77693146-2a1db400-6fa8-11ea-86e0-c36acbf0b712.png)

Is there any solution for it except union tests in one file?
Thank you in advance

[//]: # ({"businessId":"","diffLink":"","analyzers":{"js":0,"cs":0,"java":0,"acr":0,"cap":0}})

**Comment by eberfreitas** [comment]
I know it is not ideal, but have you tried to run only the tests on WSL?

**Comment by YauhenPylAurea** [comment]
Thank you for your suggestion. It is working on Ubuntu (so I suspect it is also working via WSL on Windows10).

But, in the end, I decided to merge some related to each other test files so there is a workaround for this issue in Windows 10.

I believe the issue can be closed. Thanks!

**Comment by harrysarson** [comment]
@YauhenPylAurea do you know if this is a fundamental issue with invoking the elm compiler on windows? If there a way we can pass the required number of arguments to the compiler (one arguent per test file) that avoids this error?

**Comment by YauhenPylAurea** [comment]
Hello @harrysarson, it is a common issue with Windows OS as I know. Usually, it is solved by passing parameters via a file, e.g.
```
compiler.exe C:\Temp\LongListOfParameters.txt
```
but the `compiler` should be able to read parameters from the file in this case.

As for `elm-test`, I believe `elm-test.js` is calling `elm-compiler` internally and passing paths to tests from `tests` folder by default, right? Perhaps, `elm-test.js` can be modified so it will automatically split parameters string and call compiler for each set of tests in parallel, e.g.
```
elm-compiler.exe Path1 Path2 Path3
elm-compiler.exe Path4 Path4 Path5
```
After it will combine results.

From my perspective, the issue doesn't deserve modifying the code as there is quite easy workaround.

**Comment by harrysarson** [comment]
> From my perspective, the issue doesn't deserve modifying the code as there is quite easy workaround.

Yeah, I am inclined to agree...

> After it will combine results.

...because this would be really hard.

> the compiler should be able to read parameters from the file in this case.

The `elm` exe can *only* read files from the command line (right?). If there was going to be a solution to this (and I do think is a legitimate bug) it would be getting the `elm` exe to accept arguments in a file. Fixing it in the test runner is too hard.

---

Thanks for you insight!
