### ISSUE TITLE
Some terminal behavior broken after running `elm-test`

### ISSUE THREAD

**Issue by drewolson** [elm-explorations/test#132]
I've noticed some terminal behavior is broken after running the `elm-test` command. The most obvious failure is the `ctrl+p` command to scroll through my command history. I've attached a gif of me running a `echo "hello"` command and then using `ctrl+p` to run it again. After this works, I run `elm-test` and attempt to use `ctrl+p` again. It's now broken until I issue a `ctrl+c` command.

Please let me know if I can provide any more information.

![elm-test](https://user-images.githubusercontent.com/3536/78461303-65e20900-768d-11ea-9408-9b85dc7ae145.gif)

**Comment by drewolson** [comment]
A quick update -- as far as I can tell, this only happens when I am inside of a `tmux` session.

**Comment by drathier** [comment]
On the first new bash prompt after running `elm-test`,`ctrl+r` doesn't work and arrow keys just print e.g. `^[[A` for me on mac. Pressing return or `ctrl+c` once makes things go back to normal again. 

This is most likely an issue with https://github.com/rtfeldman/node-test-runner and not with this library, though.

**Comment by drewolson** [comment]
Thanks @drathier. I've opened an issue on node-test-runner and I'll go ahead and close this one.
