### ISSUE TITLE
Installing elm-test without Node.js?

### ISSUE THREAD

**Issue by JorelAli** [elm-explorations/test#133]
Hi,

Currently the installation instructions for `elm-test` consist of installing it via the Node package manager using `npm install -g elm-test`. 

Similarly, Elm itself can be installed using `npm install -g elm`, however lately its installation procedure consists of downloading premade binaries from its GitHub page _([see here](https://github.com/elm/compiler/releases))_ which is significantly faster than installing via Node.js.

-----

Getting straight to the point - is there a way to install `elm-test` without using the node package manager? I'm trying to use `elm-test` for CI and want the fastest possible install time.

**Comment by harrysarson** [comment]
`npm i -g elm-test` installs the [node-test-runner](https://github.com/rtfeldman/node-test-runner) which is a nodejs library. nodejs is required a) to run the test runner code itself and b) to run the javascript that the elm compiler generates.

So in a word no. I am sorry!

---

Could you install elm-test without npm? You could clone the git repo and try to go that way. However, the test runner has other js dependancies which would then have to be installed (via npm).

I think you are stuck with npm alas.

**Comment by ShrykeWindgrace** [comment]
A bit of nitpicking - you can install `elm-test` and required machinery without `npm` with the help of `nix` for example (if you are willing to pay the price of learning quite a few tools).

However, as @harrysarson said, you are still bound to the `nodejs` ecosystem, you just change the package manager.

Relevant link to elm-test in nixpkgs: <https://nixos.org/nixos/packages.html?channel=nixpkgs-unstable&query=elm-test>

**Comment by harrysarson** [comment]
Closing as I think this question now has an answer!
