### ISSUE TITLE
Cannot use Fuzz.custom since Shrink module is not exposed

### ISSUE THREAD

**Issue by ianmackenzie** [elm-explorations/test#15]
Currently it appears to be impossible to use `Fuzz.custom`, since it requires providing a `Shrinker` but the only way to do that is to create one using the functions in the non-exposed `Shrink` module.

Related: the documentation for `Fuzz.custom` refers to:
  - `elm-lang/random`: should be `elm/random`, and "which is not core's Random module but has a compatible interface" should be removed
  - `eeue56/elm-shrink`, which does not exist

**Comment by mgold** [comment]
Both of these are issues in the 0.19 prerelease only (right?), but thanks for bringing them to our attention.

**Comment by ianmackenzie** [comment]
Yes - I brought this up on Slack when `elm-explorations/test` was first published a couple days ago, and @rtfeldman asked me to log it as a GitHub issue. Only an issue in 0.19 `elm-explorations/test`, 0.18 `elm-community/elm-test` is fine!

**Comment by rtfeldman** [comment]
@eeue56 do you think we should keep maintaining `Shrink` as a separate package in 0.19?

As far as I know, this is the only package that uses it, and if it's gonna end up in `elm/` long-term, we probably want to keep its dependency list as small as possible.

(If we aren't gonna have it be a separate package, then this package can just expose it and we can also start doing some `elm-test` specific optimizations on stuff like `lazy-list`.)

**Comment by rtfeldman** [comment]
@eeue56 thoughts on this? I know this is blocking some folks, so I'm inclined towards exposing it here unless you think we shouldn't!

**Comment by avh4** [comment]
Exposed in https://github.com/elm-explorations/test/pull/20 (which was also necessary to add a test case related to #18)

**Comment by avh4** [comment]
Exposed in https://package.elm-lang.org/packages/elm-explorations/test/1.1.0/
