### ISSUE TITLE
The document of `Shrink.map` has a mistake.

### ISSUE THREAD

**Issue by Hexirp** [elm-explorations/test#165]
The description of `Shrink.map` has a mistake on its code snippet.

https://github.com/elm-explorations/test/blob/74076ea9869d1ac70c8c7f674c87946784911506/src/Shrink.elm#L521-L532

It don't pass type checking.

**Comment by Hexirp** [comment]
I suggest:

1. Change the code with `map (float x) Vector |> andMap (float y) |> andMap (float x)`.
2. Change `map`'s type with `LazyList a -> (a -> b) -> LazyList b`.
3. Add `singleton : a -> LazyList a`. Change the code with `singleton Vector |> andMap (float x) |> andMap (float y) |> andMap (float x)`.

**Comment by drathier** [comment]
I don't think we should change the type of `map` so that it's only usable in applicative style. However, `andMap` mostly makes sense in applicative style, so `singleton` + `andMap` could be a pipeline friendly alternative, as in your 3rd point. Wanna make a PR?

**Comment by Hexirp** [comment]
Now, `Shrink.andMap` is deleted, because the module `Shrink` is moved to a module `Simplify`. I close this issue.
