### ISSUE TITLE
Not found modules for moved test files

### ISSUE THREAD

**Issue by ravecat** [elm-explorations/test#167]
Module not founded after move test file from `/tests`  to `/src`  folder. As I understand module can exist inside any folder in project

Test running successfully for both case `elm-test src/**/*Test.elm` and `elm-test`. 

| OK | Fail |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/24782863/114116954-57f14480-98ee-11eb-9850-4db62165988a.png) |![image](https://user-images.githubusercontent.com/24782863/114117180-c6ce9d80-98ee-11eb-9af9-9534e45fc67f.png)|

IDE - VSCode (elm-tooling available)
elm.json - [here](https://pastebin.com/BmDyPHFG)

**Comment by harrysarson** [comment]
I think this is best followed up on here https://github.com/rtfeldman/node-test-runner/issues/502. We can reopen if investigation shows this is a problem with the library not the rest runner.
