### ISSUE TITLE
Tag another release?

### ISSUE THREAD

**Issue by nmhancock** [elm-explorations/test#195]
Hi all, thanks for the project!

I have a use case where I'd like to use something like listOfLength in one of my projects, and got part way through implementing it before I realized you all had already done so.

Then I tried importing the function and noticed it wasn't being exported, and that the last tagged release was 3 years ago.

Are there any particular reasons there hasn't been a release, or items that need addressing? Maybe this issue could serve as a staging point for inhibitors.

**Comment by Janiczek** [comment]
Hey there @nmhancock! I'm planning to make a 2.0.0 release sometime this or next month.

There still are a few things to finish:
- [ ] https://github.com/elm-explorations/test/pull/187
  - and related issues in the test runners:
  - [ ] https://github.com/rtfeldman/node-test-runner/pull/614
  - [ ] https://github.com/mpizenberg/elm-test-runner/pull/13
- [ ] https://github.com/elm-explorations/test/pull/194

After those are merged, we'll coordinate with the runner maintainers to release at the same time.

Thanks for the issue - it serves as motivation to get this release out of the door sooner :)

----

In the meantime if you want to create something that behaves like `listOfLength`, you can do eg.:
```elm
listOfLength : Int -> Fuzzer a -> Fuzzer (List a)
listOfLength n itemFuzzer =
  List.repeat n itemFuzzer
    |> sequence

sequence : List (Fuzzer a) -> Fuzzer (List a)
sequence fuzzers =
    List.foldl
        (\fuzzer listFuzzer ->
            Fuzz.constant (::)
                |> Fuzz.andMap fuzzer
                |> Fuzz.andMap listFuzzer
        )
        (Fuzz.constant [])
        fuzzers
```

**Comment by Janiczek** [comment]
This is now done, 2.0.0 is released :)
