### ISSUE TITLE
Installation guide in Readme seems wrong?

### ISSUE THREAD

**Issue by craigjbass** [elm-explorations/test#28]
With a fresh project under elm 0.19...

`npm install -g elm-test` command installs elm-test 0.18.13-beta. https://www.npmjs.com/package/elm-test

When I run `elm-test init` I get the following error:

```
Created /home/cbass/Projects/projelm/tests
Created /home/cbass/Projects/projelm/tests/elm-package.json
Created /home/cbass/Projects/projelm/tests/Example.elm
/home/cbass/Projects/projelm/.gitignore already exists
/bin/sh: elm-package: command not found
Unhandled exception while running the tests: { Error: Command failed: elm-package install --yes
    at checkExecSyncError (child_process.js:611:11)
    at Object.execSync (child_process.js:648:13)
    at runElmTest (/home/cbass/.nvm/versions/node/v10.10.0/lib/node_modules/elm-test/lib/elm-test.js:291:19)
    at Object.<anonymous> (/home/cbass/.nvm/versions/node/v10.10.0/lib/node_modules/elm-test/lib/elm-test.js:742:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
  status: 127,
  signal: null,
  output: [ null, null, null ],
  pid: 4881,
  stdout: null,
  stderr: null }
```

Kinda confused?

Also started a thread here (https://elmlang.slack.com/archives/C192T0Q1E/p1537193358000100) but not sure if right place for this

**Comment by mgold** [comment]
`npm install -g elm-test@beta` for now.

**Comment by dschinkel** [comment]
@mgold can someone **please** update the readme then?

**Comment by craigjbass** [comment]
Yea for me it’s that this repo seems easy to update but there’s many references to elm-test across a lot of repos/docs. I’m not even sure where to begin? Folks should get correct guidance for elm 0.19 at the first page they’d get to in the journey when they’re trying to setup tests.

**Comment by mgold** [comment]
I've updated the README to tell you to install the beta. I think further changes will come as the dust from 0.19 settles (which should eventually include moving off the beta).

**Comment by heronils** [comment]
Thanks, `npm install -g elm-test@beta` did the job.

For the records, https://package.elm-lang.org/packages/elm-explorations/test/latest - to which this Code Repository links at the top - still says "npm install -g elm-test". https://www.npmjs.com/package/elm-test/v/0.19.0-beta11 also does.

**Comment by mgold** [comment]
The correct fix here may be to get the runner out of beta.

**Comment by heronils** [comment]
Until it is out of beta, could you replace ...

_Write unit and fuzz tests for Elm code. https://package.elm-lang.org/packages…_

... with ...

_Write unit and fuzz tests for Elm code (npm install elm-test@**beta**) https://package.elm-lang.org/packages…_

... [at the top](https://github.com/elm-explorations/test)? This would make the currently different installation procedere clear to users.

**Comment by mgold** [comment]
Runner is out of beta.
