### ISSUE TITLE
Fails on Alpine Linux

### ISSUE THREAD

**Issue by lpil** [elm-explorations/test#31]
When running `elm-test` on my CI running alpine Linux it fails like so:

```
$ elm-test
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn /opt/app/waive/assets/node_modules/elmi-to-json/unpacked_bin/elmi-to-json ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

Exited with code 1
```

Interestingly when I connect and check that file it does exist and has the right permissions, but attempting to run it results in `bash: /opt/app/waive/assets/node_modules/elmi-to-json/unpacked_bin/elmi-to-json: No such file or directory`.

I believe this is some incompatibility with Alpine Linux, possibly it's use of musl. It's common to use Alpine Linux when using Docker as it currently provides the smallest images available, so it would be beneficial for `elm-test` to work on this distribution.

**Comment by mgold** [comment]
Likely the same as rtfeldman/node-test-runner#228, try downgrading to `elm-test@0.19.0-beta8`.

**Comment by lpil** [comment]
That looks like an unrelated issue to me. I'll try downgrading, and I'll move this issue over to the runner's issue tracker.

**Comment by giovannibonetti** [comment]
@lpil Is this issue you created there related to this? https://github.com/rtfeldman/node-test-runner/issues/292

I'm struggling to run `elm-test` on Docker Alpine as well. Could you share a hint of what you did to make it work?

**Comment by drathier** [comment]
Since this is related to the test runner rather than elm-test itself, and it seems like this issue is on that bug tracker now, I'll close this issue.

**Comment by lpil** [comment]
@giovannibonetti The issue is unrelated to that one, but it is a problem with the runner. It makes use of a Haskell binary that is not statically linked and thus fails on a platform without libc. I don't remember if I opened an issue or not.

**Comment by giovannibonetti** [comment]
Thank you for opening the issue with more details, @lpil 👍
