### ISSUE TITLE
Shrinkers: how do they work?

### ISSUE THREAD

**Issue by Bastes** [elm-explorations/test#33]
![shrinkers-how-do-they-work](https://user-images.githubusercontent.com/10667/46132647-e0cb9780-c23e-11e8-8814-35c19c10e8a8.jpg)

So, I've been trying to use the `Fuzz.custom` function to work around the disappearance of `Fuzz.conditional` and `Fuzz.andThen` on a pre-existing codebase that I'm trying to migrate ; and I saw that I needed a `Random.Generator`(good, I know what they do is generate stuff randomly in a functionally pure way, and can work on one of those with `Random.andThen` and `Random.map`and other niceties) and a `Shrink.Shrinker`.

Ok, let's read the docs on this last one... those excerpts from the doc seem relevant:
```
If the fuzzer can make your test fail, it also knows how to "shrink" that failing input into more minimal examples, some of which might also cause the tests to fail.
```
Well, looks like it's a thing that does something called "shrinking" on a failing sample. Shrinking sounds like it's making things smaller. And this "shrunk" sample should attempt to make the sample fail. So far, so good.

```
type alias Shrinker a =
    a -> LazyList a

The shrinker type. A shrinker is a function that takes a value and returns a list of values that are in some sense "smaller" than the given value. If there are no such values conceptually, then the shrinker should just return the empty list.
```
So, it's an alias for a function that takes a value and returns a fancy list of values, not just one, and they need to be "smaller". What does "smaller" means in this context? Like, 0 is smaller than 1? -1 is smaller than 0? "" is smaller than "a"? Is "Z" smaller than "z"? Is "aa" smaller than "z"?...
Also, why is the word "conceptually" in this sentence?

Oh, there's another function that may make this make more sense:
```
shrink : (a -> Bool) -> Shrinker a -> a -> a

Perform shrinking. Takes a predicate that returns True if you want shrinking to continue (e.g. the test failed). Also takes a shrinker and a value to shrink. It returns the shrunken value, or the input value if no shrunken values that satisfy the predicate are found.
```
Still not sure what shrinking really is, but let's read on... Why would I want shrinking to continue, or stop? This predicate doesn't take the test as an input, why would "the test failed" be an example? Should I pass a predicate that internally reference my test itself? It returns the shrunken value. Why only one? I thought shrinkers could return multiple shrunken values? Which one will be selected?

Ok, that didn't help much. Let's see what's next. Oh, a list of shrinker constructors for many types... ok, I could use some of them if I was sure they did what I want. But I don't know what I want yet. Let's see what's next...

```
convert : (a -> b) -> (b -> a) -> Shrinker a -> b -> LazyList b
Convert a Shrinker of a's into a Shrinker of b's using two inverse functions. ) [...]
```
Ok, I see the `Shrinker a` ; where is the `Shrinker b`? Oh, right, it's the `b -> LazyList b` that's synonymous at the end of the signature...

Then I see:
```
[...] If you use this function as follows:

shrinkerB =
    f g shrinkerA
Make sure that

`f(g(x)) == x` for all x
Or else this process will generate garbage.
```
Wait... what? What is `f`? What is `g`? Why would I use `f g shrinkerA`? Where does it have to do with `convert`? It will generate garbage unless `f(g(x)) == x for all x`? I thought `f` was a function that took two arguments (`g` and `shrinkerA`) so why does it takes only one in the `f(g(x)) == x` law? Is x a function too?

I'll stop here, I guess you understand my point: this is confusing for someone who doesn't already know what shrinkers are, what they're meant to do, and why we need them to work with the Generators to make Fuzzers. And this is kinda important for someone who wants to make their own Fuzzers to understand them, especially when functions like `Fuzz.andThen` and `Fuzz.conditional` are deprecated.

Since I'd rather help than give someone else work, I'd love to write a documentation that takes the user by the hand when they try to wrap their head around the subject, but I'd have to understand what Shrinkers are, what they do and why first (and right now, it's still quite fuzzy for me :p).

So, if someone in this fine team would like to take a moment and help me get the basics on Fuzzers so I can send a documentation PR, I'd be happy to do just that in return ;)

**Comment by Bastes** [comment]
My pleasure :) thanks for the explanations, it's a lot clearer now (and better than my previous intuition on the matter ;p) ; I'll prepare a little something in a PR, but I can't tell yet when it's done (hopefully in the next week, maybe more accurately in the next few weeks). If you want, you can keep this issue open and assign me to it.

PR you soon :)

**Comment by harrysarson** [comment]
I have never understood shrinkers, thanks for offering to help with this one and I eagerly await the new and shiny docs.

**Comment by Bastes** [comment]
Well, here's my first attempt:
https://github.com/elm-explorations/test/pull/35

Have fun :)

**Comment by drathier** [comment]
Guess we can close this now that #35 is merged :)

**Comment by Bastes** [comment]
For sure :)
