### ISSUE TITLE
Rename Shrinker -> Simplifier?

### ISSUE THREAD

**Issue by harrysarson** [elm-explorations/test#36]
Hi,

May I give a suggestion: rename the `Shrinker` type to `Simplifier`.

This is a suggestion that occurred to me whilst reading through #33 but I thought it worth making a new issue rather than derailing that one.

Following the (de-facto?) principle of using descriptive names in elm, I thought that the meaning of "shrinking a test input" would have been much clearer to me if it had instead been called "simplifying a test input".

From @mgold's comment: https://github.com/elm-explorations/test/issues/33#issuecomment-425282488

> Let's say I have a test that claims every integer is even. You'll get around 50 failing tests, each with a different odd number. The goal of the shrinker is to tell you that 1 is the "smallest" or "simplest" counterexample to your claim. 1 is ~~"larger"~~ "smaller" than -1, somewhat by convention.

Feel free to close if such a change is not appropriate, or if github is not the appropriate place to make such a suggestion.

Cheers :+1:

**Comment by drathier** [comment]
I'm all for this. We should also change all references of "smaller" values to "simpler" values.

**Comment by mgold** [comment]
Seems like a good idea, unfortunately it's a breaking change. Applying the appropriate tag.

**Comment by Bastes** [comment]
Ooooh, that sounds like a great idea indeed :)

**Comment by rtfeldman** [comment]
I dig this! Does anyone want to take a pass at a PR?

**Comment by harrysarson** [comment]
Would it be worth keeping 'Shrinker` around for a version or two as an alias?

**Comment by Bastes** [comment]
You know what? I'll have a go at a PR on this :)
