### ISSUE TITLE
Rename tuple and tuple3 into pair and triple?

### ISSUE THREAD

**Issue by drathier** [elm-explorations/test#48]
Since we only have two sizes of tuples, I feel like we could see if we can give the two distinct names. Thoughts?

**Comment by mgold** [comment]
I really like this idea, and I hope I'm not premature in applying the major release blocker tag since it will be a breaking change.

**Comment by mgold** [comment]
If we're doing a minor release for some reason, we can add these and keep the old names as deprecated, to give people time to change over.

**Comment by drathier** [comment]
Assuming you meant `major release`?

**Comment by rtfeldman** [comment]
I'm mostly kidding, but every time I think "threeple" I smile. 😄

**Comment by drathier** [comment]
`twople` and `threeple` are perfect troll names to use in presentations 😂 Specially since `Twople` sounds fairly close to `tuple`, but not quite.

**Comment by mgold** [comment]
@harrysarson Can you please make a PR with the rename? I don't think we should bother with aliases; just rename them.

**Comment by harrysarson** [comment]
Thoughts on `tripple` vs `tripplet`?
