### ISSUE TITLE
Invalid Package Dependencies when using elm/file

### ISSUE THREAD

**Issue by folkertdev** [elm-explorations/test#54]
There seems to be a version conflict with elm-test and `elm/file`, to reproduce:

* `mkdir elm-test-bug`
* `cd elm-test-bug`
* `elm init`
* `elm-test init`
* `elm-test`; this works
* `elm install elm/file`
* `elm-test` fails because somehow the dependencies are not compatible

Additionally, adding `elm-explorations/test` as a dependency works just fine, so it looks like the problem is in elm-test itself.

**Comment by LukeWoodward** [comment]
It seems the package with the compatibility problem is `elm/json`, and making this a direct rather than an indirect dependency gets rid of the problem.

I was able to reproduce the problem by following the reproduction steps above.  After running `elm install elm/json`, `elm-test` started working again.

**Comment by perty** [comment]
I reported this, by mistake, elsewhere:

When installing elm/http, elm-test stops working with the error message "The dependencies in your elm.json are not compatible."

To reproduce:
1. Create a directory and cd into it.
2. Run elm-init
3. Run elm-test init
4. Run elm-test. Works as expected with the Example executing
5. Run elm install elm/http. Breaks with error message above.

Resulting elm.json
```
{
    "type": "application",
    "source-directories": [
        "src"
    ],
    "elm-version": "0.19.0",
    "dependencies": {
        "direct": {
            "elm/browser": "1.0.1",
            "elm/core": "1.0.2",
            "elm/html": "1.0.0",
            "elm/http": "2.0.0"
        },
        "indirect": {
            "elm/bytes": "1.0.7",
            "elm/file": "1.0.1",
            "elm/json": "1.1.2",
            "elm/time": "1.0.0",
            "elm/url": "1.0.0",
            "elm/virtual-dom": "1.0.2"
        }
    },
    "test-dependencies": {
        "direct": {
            "elm-explorations/test": "1.2.0"
        },
        "indirect": {
            "elm/random": "1.0.0"
        }
    }
}
```

**Comment by folkertdev** [comment]
@perty Does the fix suggested work for you? I switched my project to be a `"package"` (this was the plan anyway) and those only have direct dependencies and version ranges. That made the version constraint solver happy apparently.

**Comment by perty** [comment]
Yes, that worked, thank you.

**Comment by drathier** [comment]
Does that mean that this issue is solved for you? Looks like an issue with the version constraint solver or installation process in the compiler, rather than in elm-test. Either way, it's more related to the test runner, not the elm-test package.

**Comment by folkertdev** [comment]
Yes it's solved (or at least there is a practical fix).

Would an issue on the node-test-runner repo be helpful, or is this likely a problem that won't come up again?

**Comment by objarni** [comment]
Bumped into this problem today getting elm-test to run on a Ubuntu 18.04 desktop machine.

`elm install elm/json`

.. fixed it. It seems elm-test has some unspecified/unclear dependency on elm/json?
