### ISSUE TITLE
elm-html-test README.md

### ISSUE THREAD

**Issue by andys8** [elm-explorations/test#56]
@avh4 did a great job moving [`elm-html-test`](https://package.elm-lang.org/packages/eeue56/elm-html-test/latest) into `elm-explorations/test` (thx :+1: ).

If I'm not mistaken the [`README.md` of that package](https://github.com/eeue56/elm-html-test/blob/5.2.0/README.md) got lost. It explains the general usage of the package.

We could:
1. Add it to the [`README.md`](https://github.com/elm-explorations/test/blob/master/README.md) (but it will bloat it)
2. Add it to a package (e.g. [Query](https://package.elm-lang.org/packages/elm-explorations/test/latest/Test-Html-Query)) (but it has to be part of the elm file).
3. Add it as separate markdown file and link to it from the main `README.md` (my favorite)

**Comment by avh4** [comment]
Yep, duplicate of https://github.com/elm-explorations/test/issues/51 :)

**Comment by andys8** [comment]
Mhhh ^^ Closing the duplicate.
