### ISSUE TITLE
How do I make my own Shrinkers?

### ISSUE THREAD

**Issue by tmohme** [elm-explorations/test#66]
The documentation in `Shrink.elm` v1.2.0 says about this topic 

> Shrinkers have to return a LazyList

. . . but unfortunately with corresponding types (or helper functions) are not exposed, making it for some cases hard to write a `Shrinker`.  
While many custom shrinkers can be easily composed by using the provided shrinkers and helper functions, this is not the case for ADTs (like `type abc = A | B | C`) - at least I haven't found a way to do this.

My current use case is very similar to creating a shrinker for `Maybe` - just for a custom type.

Please expose appropriate functions to achieve this and/or adjust the documentation to more elaborately explain creating custom shrinkers. 

Edit:
I finally achieved my goals by composing Fuzzers (instead of Shrinkers - in so far it was my fault).
Nevertheless, the documentation for this topic seems misleading (since elm 0.19) as the given advice can't be followed because the mentioned type `LazyList` is no longer exposed.

**Comment by mgold** [comment]
This was fixed by #35, which apparently hasn't been released. You can look at a [more recent version of the file](https://github.com/Bastes/test/blob/7e9151c853460a763a2d1cccb1b15c191d70afa0/src/Shrink.elm) for more information.

**Comment by tmohme** [comment]
Maybe my initial description of the problem was a bit confused . . . sorry for that.
I find the general description of what a Shrinker / Simplifier has to do pretty clear.

The paragraphs in question (starting at [L#133](https://github.com/elm-explorations/test/blob/5920eab1e7f51f100d86d3440bcb90d8d4ff1229/src/Simplify.elm#L133)) essentially haven't changed between v1.2.0 and now (except the naming change Shrinker->Simplifier).
The second and third paragraph tell the reader to return a `LazyList` (which is just plain text for the type alias in [L#173](https://github.com/elm-explorations/test/blob/5920eab1e7f51f100d86d3440bcb90d8d4ff1229/src/Simplify.elm#L133)).
The problem is, that `LazyList` is not accessible outside the package because the module is not exposed, so any reader beyond the package maintainers is effectively unable to follow this advice.

This conflict could be solved in different ways:
- expose module LazyList
- expose some helper functions to create a LazyList (like `singleton`,...) & adapt the description
- only change the description for "How do I make my own Simplifiers?"
- ...

Each of these approaches have different pros and cons that must be understood to make a good decision. I don't suggest any particular solution because I think my understanding of the package is way too incomplete.

But maybe I have missed something fundamental and don't fully understand the situation / overestimate the problem? In this case I would be thankful for an explanation.

**Comment by harrysarson** [comment]
> The problem is, that LazyList is not accessible outside the package because the module is not exposed

That is definitely a problem which needs addressing.

**Comment by drathier** [comment]
Could we see if we can avoid exposing lazylist, and instead use normal lists in the public api?

**Comment by tmohme** [comment]
It's several months that this change took effect and apparently I'm the only one who stumbled about this inconsistency - and that only happened because I initially took the wrong route and tried to build my own Shrinker instead of solving the problem on a higher (= fuzzer) level.  
Also, the supply of shrinkers for the basic types looks pretty exhaustive.  
Only for the custom ADT niche I see the need to add "something".
Although obviously not complete, a simple `singleton : a -> a -> LazyList a` shrinker (creating a LazyList with the provided argument) would probably be helpful for many use-cases in the ADT niche - at least I would have been helpful for mine.
Apart from that, for now a simple documentation change (along the lines "Currently creating your own shrinker is not possible. Please try to achieve your goals by composing provided shrinkers or fuzzers.") seems perfectly legit to me.

**Comment by mgold** [comment]
> Could we see if we can avoid exposing lazylist, and instead use normal lists in the public API?

That's not a terrible idea. I think it would simplify the API a lot and prevent people from writing shrinkers that tried an infinite number of values.

The downside is that you will generate and allocate values that may not be needed for shrinking. Let's say you generate a list length ten, so ten possible shrinks for the value. If the first value caused the test to fail, then all of the other values are wasted. (You only generate them if you have a failing test, so the passing case is unaffected.)

We would of course need to do performance benchmarking to back all of this up.

**Comment by mgold** [comment]
I think that the perf impact of switching from lazy lists to lists *in the public API* should be minimal. Each layer of the rose tree is still lazy, so you only generate extra values when you shrink one value. The shrinks of those values are still lazy.
