### ISSUE TITLE
Simplify.lazylist cannot be used

### ISSUE THREAD

**Issue by harrysarson** [elm-explorations/test#67]
https://package.elm-lang.org/packages/elm-explorations/test/latest/Shrink#lazylist

The function `Simplify.lazylist` has this type signature (note it takes a `LazyList` as an argument):

```elm
lazylist : Shrinker a -> LazyList a -> LazyList (LazyList a)
```

However, `LazyList` is not exposed by this package so there is no way that a user can get their hands on a `LazyList` to pass to `Simplify.lazylist`. Therefore, (unless I am wrong - entirely possible) there is no way to call this function.

Either:
* Expose `LazyList`
* Remove this function.

Refs: #66 
cc:  @tmohme

**Comment by mgold** [comment]
Adding major release blocker keyword because of the potential breaking API change.

**Comment by tmohme** [comment]
@harrysarson  
With the following snippet I'm able to use the `lazylist` function:
```
import Shrink

--f : Int -> LazyList (LazyList Int)
f valueToShrink = 
    Shrink.lazylist Shrink.int (Shrink.int valueToShrink)

```
But . . .
* the example only compiles if you don't use type annotations
* this example probably doesn't make a lot of sense and I wonder if there is a real world use-case that does (under the given restrictions)
* I'm not sure if I missed some other important point as I'm not that experienced with elm yet

**Comment by mgold** [comment]
The purpose of this function is to simplify lazy lists, and in 0.19 there is not a standard implementation of lazy, or lazy lists. So I think the correct thing to do is to remove this function.
