### ISSUE TITLE
Add the ability to customize the path of test files through elm.json

### ISSUE THREAD

**Issue by ravicious** [elm-explorations/test#69]
There's already #34 which is about running tests that live in a non-standard directory. Fortunately, this can now be easily done through `elm-test path/to/that/dir`.

I believe that ultimately there should be a way to specify the custom paths for tests in a config file. If `elm-test` allows you to run tests that are not in `<root_dir>/tests`, then I think it should also allow for specifying that custom paths in `elm.json` so that 3rd party tools can support that use case as well.

Let me explain my specific scenario: @altaurog added support for 0.19 in ale (a vim plugin) in https://github.com/w0rp/ale/pull/2176 (thanks for that!) which corresponds to the issue #64. The code assumes that tests are at `<root_dir>/tests`. We have a Rails app with frontend in Elm and the Elm tests live in `app/javascript/tests`, so that fix doesn't work for me in that project.

In our scenario we can freely move those Elm tests to `<root_dir>/tests`, but I imagine that in the future someone won't have this luxury.

---

This is just the first thing that came to my mind, perhaps there are other ways to solve this problem and I'm open to hear them!

**Comment by ravicious** [comment]
Well, now that I think about it, I got a bit ahead of myself when it comes to suggesting this particular solution. I think the core problem is that `elm make` is not able to compile test files as described in #64, so editor plugins have to run `elm test make` for test files instead. The only way to check if a file is a test file or not seems to be checking its path.

I took a look at vscode Elm plugin and it does exactly the same thing, with the exception that the plugin allows you to configure the path under which you have your tests.

That's an acceptable workaround for now, but still, having `elm make` work on test files would solve the problem altogether. Do you think this is something I should bring up in the elm/compiler repo or do you perhaps know that this topic has already been discussed somewhere? I looked at the issues in elm/compiler and threads on discourse, but I didn't find anything.

**Comment by mgold** [comment]
I don't think there's a way to make `elm-make` work on test files without including your tests as part of your package, hence the hack of a separate `elm.json` in a subdirectory.
