### ISSUE TITLE
API fatal error handler returned after process out of memory

### ISSUE THREAD

**Issue by glasserc** [elm-explorations/test#82]
(Sorry if this isn't the right repository, I'm a little at a loss here...)

I have a set of tests in a private project that fails to run. I'm relatively certain that the failure does not represent a bug in the test or the code (i.e. I don't think it's https://github.com/rtfeldman/node-test-runner/issues/290). I haven't tried boiling things down to an SSCCE yet, but will try next. (I wanted to make sure I didn't lose the stack traces.) Here are the error messages I've gotten:

```
> elm-test

elm-test 0.19.0-rev5
--------------------

Running 14 tests. To reproduce these results, run: elm-test --fuzz 100 --seed 396170984152586 [...]


#
# Fatal error in , line 0
# API fatal error handler returned after process out of memory
#
```

and

```
> elm-test

elm-test 0.19.0-rev5
--------------------

Running 14 tests. To reproduce these results, run: elm-test --fuzz 100 --seed 215354435481898 [...]


<--- Last few GCs --->

[17089:0x380a230]   141745 ms: Mark-sweep 1408.2 (1460.8) -> 1408.2 (1444.8) MB, 3321.9 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 3322 ms) last resort 
[17089:0x380a230]   145181 ms: Mark-sweep 1408.2 (1444.8) -> 1408.2 (1444.8) MB, 3435.9 / 0.0 ms  last resort 


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x219007da8799 <JSObject>
    1: /* anonymous */ [/home/ethan/src/quartermaster/frontend/elm-stuff/generated-code/elm-explorations/test/elmTestOutput.js:~10389] [pc=0x467f709e9e1](this=0xd99f2d746f1 <JSFunction (sfi = 0x13127ca2071)>,hour=10,minute=26,second=23)
    2: /* anonymous */(aka /* anonymous */) [/home/ethan/src/quartermaster/frontend/elm-stuff/generated-code/elm-explorations/test/elmTestOutput.js:~10416] [pc=0...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/home/ethan/.nvm/versions/node/v8.5.0/bin/node]
 2: 0x13576dc [/home/ethan/.nvm/versions/node/v8.5.0/bin/node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [/home/ethan/.nvm/versions/node/v8.5.0/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/home/ethan/.nvm/versions/node/v8.5.0/bin/node]
 5: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/home/ethan/.nvm/versions/node/v8.5.0/bin/node]
 6: v8::internal::Runtime_AllocateInTargetSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/home/ethan/.nvm/versions/node/v8.5.0/bin/node]
 7: 0x467f6f046fd
```

After either message, `elm-test` hangs (doesn't finish in 6-7 minutes) and I have to kill it with Ctrl-C.

Rerunning the tests with the same seed causes the same message, but rerunning the tests with a new seed can produce either message or even succeed after a very long time (~3 min vs. the usual ~15 seconds).

Although the message is about OOMing, my computer still has plenty of free RAM (~2GB according to `top`). I'm guessing node is exhausting some pre-allocated heap, but I couldn't figure out how to enlarge that heap (unlike e.g. https://github.com/elm-explorations/test/issues/22#issuecomment-419544972).

I suspect there's something about my tests and/or fuzzers that consume an awful lot of memory but I haven't figured out exactly what it is. When I try to disable certain parts of my fuzzers I can circumvent the error. In particular, I have had a lot of success converting `Fuzz.list a` into `Fuzz.map (\elem -> [elem]) a`. Of course this limits the utility of the test.

**Comment by avh4** [comment]
Can you try with elm-test CLI 0.19.0-rev6 ?

Also, what version of elm-explorations/test are you using in your elm.json?  (Latest is 1.2.1, and some older versions did have some bugs where printing certain test failures would exhaust the stack.)

**Comment by glasserc** [comment]
I was using CLI 0.19.0-rev5 and elm-explorations/test 1.2.0. The failure seems to reproduce under -rev6 and 1.2.1.

**Comment by glasserc** [comment]
Here is an SCCEE:

```
module Example exposing (..)

import Expect exposing (Expectation)
import Fuzz exposing (Fuzzer, int, list, string)
import List exposing (foldl)
import Test exposing (..)
import Tuple exposing (first)


type alias Directory =
    { directory : List Video
    }


type alias Video =
    { frames : List Frame
    }


type alias Frame =
    { segments : List Segment
    }


type alias Segment = ( Point, Point )

type alias Point =
    { x : Int
    , y : Int
    , z : Int
    }


point : Fuzzer Point
point =
    Fuzz.map Point (Fuzz.int)
        |> Fuzz.andMap (Fuzz.int)
        |> Fuzz.andMap (Fuzz.int)


segment : Fuzzer Segment
segment = Fuzz.tuple ( point, point )


frame : Fuzzer Frame
frame = Fuzz.map Frame (Fuzz.list segment)


video : Fuzzer Video
video = Fuzz.map Video (Fuzz.list frame)


directory : Fuzzer Directory
directory = Fuzz.map Directory (Fuzz.list video)


suite : Test
suite =
    describe "Longest word"
        [ fuzz directory "Adding a short word to a document changes nothing" <|
              \d -> Expect.true "hi" True
        ]
```

It seems pretty clear that the basic problem is the nested use of `Fuzz.list`. Indeed per https://github.com/elm-explorations/test/blob/42c50e0a241c39b4df0de9e83e6e79af0e031b79/src/Fuzz.elm#L363 it seems like a given call to `Fuzz.list` could produce up to 400 of the given elements. Since I have three nested `List`s, I have a theoretical maximum of 128M `Point` (because 2 per segment). I don't know how much memory each one takes up (incl. cons cells?) but I can imagine a conservative memory limit which cuts things off by then. I certainly didn't realize how fast memory usage was going to explode here.

It turns out for my application that I don't actually need to store data in exactly this way so I can probably reduce memory usage. It's a bit of a pity because there's no way to set limits on the size of `list` generated (nor is there a natural way to generate other non-`List` types like `Dict` or `Set`).

I guess this is PEBKAC so I'll close it unless you can think of a clever way to prevent people from shooting themselves in the foot like this.
